name: admin-ui-general-settings
namespace: official
version: 1.1.0-1
author: Wazo Team
display_name: General Settings
min_wazo_version: 18.02
tags:
  - settings
homepage: https://github.com/wazo-pbx/wazo-admin-ui-general-settings
